version: '3'

services:
  app:
    image: $CONTAINER_RELEASE_IMAGE
    container_name: addispay_dev
    restart: unless-stopped
    ports:
      - "4050:8000"
    env_file: .env
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: addispay_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: addispay
      MYSQL_ROOT_PASSWORD: addispay
      MYSQL_USER: addispay
      MYSQL_PASSWORD: addispay

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: addispay_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: addispay
